// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3eb1QpXyiHVWRfeeaoXksUd6-ya4veoo',
    appId: '1:985913852881:web:7372ce41dfd57adcf396f0',
    messagingSenderId: '985913852881',
    projectId: 'smoe-d5f68',
    authDomain: 'smoe-d5f68.firebaseapp.com',
    storageBucket: 'smoe-d5f68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wELx0j8_j2Nnml7FS-C9xycHZcCj6jM',
    appId: '1:985913852881:android:9e8b4a533f8af644f396f0',
    messagingSenderId: '985913852881',
    projectId: 'smoe-d5f68',
    storageBucket: 'smoe-d5f68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6gTc5gL2f8pQeP77ZCFiCkMJSFYWXLkw',
    appId: '1:985913852881:ios:73e3c5b79b7e08bdf396f0',
    messagingSenderId: '985913852881',
    projectId: 'smoe-d5f68',
    storageBucket: 'smoe-d5f68.appspot.com',
    iosBundleId: 'com.example.smoeDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6gTc5gL2f8pQeP77ZCFiCkMJSFYWXLkw',
    appId: '1:985913852881:ios:83cbead354dde982f396f0',
    messagingSenderId: '985913852881',
    projectId: 'smoe-d5f68',
    storageBucket: 'smoe-d5f68.appspot.com',
    iosBundleId: 'com.example.smoeDashboard.RunnerTests',
  );
}
